### ISSUE TITLE
keep images without annotation

### ISSUE THREAD

**Issue by vincentlux** [pylabel-project/pylabel#56]
Hi, thanks for opensourcing this great tool! It's quite helpful. Do you know if there is a walk-around that I can use to keep the image information for images that do not have annotations? For example, if one image does not have any annotation, ideally it will be kept in the "images" field when exported to the coco format.

**Comment by alexheat** [comment]
Hello I understand your requirement @vincentlux . I have done some special work to handle images that don't have any annotations but it sounds like it is not working perfectly yet. Including a reference to the image in the coco file output sounds like the ideal behavior to me too. 

Could you possibly share the dataset that you are using for testing (and your code as well) so that I can make sure it works for type of dataset?

**Comment by vincentlux** [comment]
Thanks for the quick reply! I currently don't have a public dataset with background images in hand... I want to add images without annotations because I am trying to [add background images to object detection models](https://github.com/ultralytics/yolov5/issues/12#issuecomment-976797725) to reduce False Positive cases. Adding this to YOLOv5 dataset is easy (just copy/paste images to the ./images folder), but then I got the problem I mentioned when converting to coco data format...

**Comment by alexheat** [comment]
Hello @vincentlux. I think this will work if you create an  empty annotation files for each of the images. For example if you add background1.jpg create an annotation file called background1.txt. The file can be empty, with no labels. 

Can you try that? 

I read that link that you provided above and I think that even the yolo models will require the empty annotation files in order to include the background images when training. I saw a comment that said "No labels are required for background images." I think that means that no labels are required within the annotation files but the annotation files are still required.
