### ISSUE TITLE
YOLOv5 class index starts from 1

### ISSUE THREAD

**Issue by ahmadSum1** [pylabel-project/pylabel#99]
As per the official YOLOv5 repository, class labels are indexed from 0 but the example script for coco2yolov5.ipynb generates label texts starting from 1. 
Here is what I have:

> Number of images: 1547
> Number of classes: 5
> Classes:['swimmer', 'boat', 'jetski', 'life_saving_appliances', 'buoy']
> Class counts:
> swimmer                   6206
> boat                      2214
> buoy                       560
> life_saving_appliances     330
> jetski                     320

the yaml file looks like this:
```
names:
- swimmer
- boat
- jetski
- life_saving_appliances
- buoy
nc: 5
path: ..
train: training/images
val: training/images
```
see the image below, the image has only 'swimmer' and 'boat'. so class '0' and '1'
but the annotation file looks like this:

> 85.txt
```
2 0.4557 0.0825 0.0138 0.0364
2 0.5967 0.5397 0.0146 0.0332
2 0.7602 0.4009 0.0260 0.0236
2 0.6354 0.3676 0.0171 0.0364
1 0.7069 0.3532 0.0122 0.0139
1 0.6837 0.3601 0.0114 0.0150
```

![image](https://user-images.githubusercontent.com/17803699/230716807-b282223b-b6d0-4611-8927-c1b08de5c3bf.png)

**Comment by ahmadSum1** [comment]
a workaround is 
`dataset.export.ExportToYoloV5( cat_id_index=0)` but the default should have been 0
I had to go through the source code to find this and I must say, this is a well-written library with some potential features that are buried inside for lack of proper documentation.

**Comment by alexheat** [comment]
Hello @ahmadSum1 , I do have documentation but it was not building correctly. After I got your message I found the problem and republished the documentation. Does this look better? https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel-exporter-module

Would you call this proper documentation? 

I did try to document the functions well. 

My philosophy is to change the original datasets as little as possible by default since doing so can can other types of confusion. (For example if the user things the first class is a 1 but I have changed it to 0)

**Comment by ahmadSum1** [comment]
Thanks for the response.
The documentation look good 😄
About the class index, i wonder whether Ultralytics changed something or not in the recent years!? 
Makesense.ai yolo label exporter has the same issue, class index starts at 1.
Which messes things up in roboflow.

**Comment by alexheat** [comment]
I am not sure what the history is, but it is not consistent across
different tools and frameworks. A previous user found the same problem and
created this reindixing feature
